// All user-facing text lives here so a translation can be added later.

export const strings = {
  appName: 'Training Tracker',

  tabs: {
    today: 'Today',
    history: 'History',
    progress: 'Progress',
    body: 'Body',
    settings: 'Settings',
  },

  placeholder: {
    comingInPhase: (phase: number) => `Coming in phase ${phase}.`,
  },

  common: {
    loading: 'Loading…',
    cancel: 'Cancel',
    kg: 'kg',
    offlineNeeded: 'You need to be online for this.',
  },

  sync: {
    allSaved: 'All saved ✓',
    waiting: (n: number) => `${n} ${n === 1 ? 'change' : 'changes'} waiting to sync`,
    syncing: 'Syncing…',
    offline: 'Offline',
  },

  auth: {
    email: 'Email',
    password: 'Password',
    newPassword: 'New password',
    displayName: 'Your name',
    logIn: 'Log in',
    signUp: 'Create account',
    forgot: 'Forgot password?',
    noAccount: 'No account yet?',
    haveAccount: 'Already have an account?',
    backToLogin: 'Back to log in',
    sendReset: 'Send reset link',
    resetSent: 'If an account exists for that email, a reset link is on its way.',
    setPassword: 'Set new password',
    passwordUpdated: 'Password updated.',
    checkEmail: 'Check your email to confirm your account, then log in.',
    resetTitle: 'Reset password',
    resetInvalid: 'This reset link is invalid or has expired. Request a new one.',
    passwordHint: 'At least 8 characters.',
    passwordTooShort: 'Password must be at least 8 characters.',
    otherAccountPending: (n: number) =>
      `This device still has ${n} unsynced ${n === 1 ? 'change' : 'changes'} from another account. Log in with that account and let it sync before switching.`,
    logOutThisAccount: 'Log out of this account',
  },

  weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  weekdaysLong: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],

  describe: {
    sets: (sets: number, reps: number) => `${sets}×${reps}`,
    at: (kg: string) => `@ ${kg}`,
    seconds: (s: number) => `${s} s`,
    minutes: (m: number) => `${m} min`,
    or: ' · ',
    warmup: (min: string) => `${min} warm-up`,
    cooldown: (min: string) => `${min} cool-down`,
    hardEasy: (work: string, rec: string, rounds: string) => `${work} hard / ${rec} easy × ${rounds}`,
    fixed: 'Fixed targets',
    linear: (inc: string, fails: number, pct: number, min: string) =>
      `+${inc} when every set hits its reps · after ${fails} failed sessions drop ${pct}% (never below ${min})`,
    reps: (inc: number, max: number) => `+${inc} rep per set after a good session, up to ${max}`,
    step: (amount: string, weeks: number, cap: string) =>
      `+${amount} every ${weeks === 1 ? 'week' : `${weeks} weeks`}, up to ${cap}`,
    workTime: 'work time',
    optional: 'optional',
    onlyOn: (days: string) => `${days} only`,
    rest: 'Rest',
    rotation: (name: string) => `Next from ${name}`,
    ongoing: 'Ongoing',
    weeks: (n: number) => `${n} weeks`,
    perWeek: (n: number) => `${n} ${n === 1 ? 'session' : 'sessions'} a week`,
  },

  plans: {
    title: 'Plans',
    newPlan: 'New plan',
    active: 'Active',
    drafts: 'Drafts',
    others: 'Other plans',
    none: 'No plans yet.',
    edit: 'Edit',
    continueDraft: 'Continue',
    duplicate: 'Duplicate',
    activate: 'Activate',
    archive: 'Archive',
    discard: 'Discard',
    discardConfirm: 'Discard this draft?',
    copyName: (name: string) => `${name} (copy)`,
    unsavedEdits: 'Unsaved changes',
    startsOn: (date: string) => `Starts ${date}`,

    chooseTitle: 'Choose a starting point',
    chooseIntro: 'Pick a template to copy into your own plan (everything stays editable) or start from scratch.',
    scratchName: 'Build from scratch',
    scratchDescription: 'Start with an empty plan.',

    steps: ['Basics', 'Workouts', 'Schedule', 'Reminders', 'Review'],
    back: 'Back',
    next: 'Next',
    save: 'Save plan',
    saveAndActivate: 'Save and activate',
    draftSaved: 'Draft saved',
    editsSaved: 'Changes kept on this device until you save',
    discardEdits: 'Discard changes',
    restoredEdits: 'Unsaved changes from last time were restored.',
    notFound: 'This plan could not be found.',
    fixErrors: 'Some fields need fixing before you can continue.',

    name: 'Plan name',
    goal: 'Goal',
    goalPlaceholder: 'e.g. lose 10 kg, run 5K',
    startDate: 'Start date',
    length: 'Length',
    ongoing: 'Ongoing',
    fixedWeeks: 'Fixed number of weeks',
    weeks: 'Weeks',

    workout: 'Workout',
    workoutName: 'Workout name',
    addWorkout: 'Add workout',
    newWorkoutName: (n: number) => `Workout ${n}`,
    removeWorkout: 'Remove workout',
    removeWorkoutConfirm: (name: string) => `Remove "${name}" and its exercises?`,
    addItem: 'Add exercise',
    noItems: 'No exercises yet.',
    dragHandle: 'Drag to reorder',

    pickerTitle: 'Add to workout',
    search: 'Search exercises',
    categories: {
      barbell_gym: 'Barbell & gym',
      bodyweight: 'Bodyweight',
      conditioning: 'Conditioning',
      running: 'Running',
      custom: 'Your exercises',
    },
    special: 'Runs & other',
    addRun: 'Run',
    addRunHint: 'Duration and/or distance',
    addIntervals: 'Intervals',
    addIntervalsHint: 'Warm-up, work/recovery rounds, cool-down',
    addFree: 'Free item',
    addFreeHint: 'Anything else, e.g. a finisher',
    newExercise: 'Create custom exercise',
    exerciseName: 'Exercise name',
    exerciseType: 'Type',
    usesBarbell: 'Uses a barbell (never below 20 kg)',
    increment: 'Weight step (kg)',
    createAndAdd: 'Create and add',
    types: {
      weight_reps: 'Weight × reps',
      bodyweight_reps: 'Bodyweight reps',
      timed: 'Timed',
      run_continuous: 'Run',
      run_intervals: 'Intervals',
      free: 'Free',
    },

    itemTitle: 'Edit exercise',
    done: 'Done',
    removeItem: 'Remove from workout',
    exercise: 'Exercise',
    sets: 'Sets',
    reps: 'Reps',
    startWeight: 'Start weight (kg)',
    rest: 'Rest (s)',
    hardRest: '"Hard" button rest (s)',
    failedRest: 'Rest after a failed set (s)',
    seconds: 'Seconds',
    label: 'Name',
    durationMin: 'Duration (min)',
    distanceKm: 'Distance (km)',
    paceNote: 'Pace note',
    warmupMin: 'Warm-up (min)',
    workS: 'Work (s)',
    recoveryS: 'Recovery (s)',
    roundsMin: 'Rounds (min)',
    roundsMax: 'Rounds (max)',
    cooldownMin: 'Cool-down (min)',
    cooldownMaxMin: 'Cool-down up to (min)',
    effortNote: 'Effort note',
    titleField: 'Title',
    description: 'Description',
    optionalItem: 'Optional',
    onlyOnDays: 'Only on these days',
    everyDay: 'Leave empty for every day',
    progression: 'Progression',
    progressionKinds: { none: 'None (fixed)', linear: 'Linear weight', reps: 'Add reps', step: 'Step up over time' },
    incrementKg: 'Add per success (kg)',
    failures: 'Failed sessions before deload',
    deloadPct: 'Deload (%)',
    roundTo: 'Round to (kg)',
    minWeight: 'Never below (kg)',
    addReps: 'Add reps per set',
    maxReps: 'Max reps',
    stepField: 'What grows',
    stepFields: { duration_min: 'Duration (min)', distance_km: 'Distance (km)', work_s: 'Work time (s)' },
    stepAmount: 'Add',
    everyWeeks: 'Every N weeks',
    cap: 'Up to',

    rotations: 'Rotations',
    rotationsHint: 'A rotation slot gives the next workout after the last one you completed, whatever the day.',
    addRotation: 'Add rotation',
    rotationName: 'Rotation name',
    newRotationName: (n: number) => `Rotation ${n}`,
    addToRotation: 'Add workout…',
    removeRotation: 'Remove rotation',
    weekSchedule: 'Week',
    slotRest: 'Rest',
    slotWorkout: (name: string) => name,
    slotRotation: (name: string) => `Rotation: ${name}`,

    reminders: 'Reminders',
    remindersHint: 'Daily reminder with what to do that day. You can turn on notifications in Settings.',
    remindersOn: 'Send reminders',
    reminderTime: 'Time',
    reminderDays: 'Remind me on',
    weighIns: 'Weigh-in reminders on',

    reviewSchedule: 'Schedule',
    reviewWorkouts: 'Workouts',
    reviewReminders: 'Reminders',
    remindersOff: 'Off',
    remindersSummary: (time: string, days: string) => `${time} on ${days}`,
    weighInSummary: (days: string) => `Weigh-ins: ${days}`,
  },

  today: {
    title: 'Today',
    noPlan: 'No active plan yet.',
    choosePlan: 'Choose a training plan',
    plansLink: 'Plans',
    activePlan: 'Active plan',
    todayIs: (workout: string) => `Today: ${workout}`,
    restDay: 'Today is a rest day.',
    loggingSoon: 'Workout logging arrives in phase 4.',
  },
  history: {
    title: 'History',
    empty: 'Your logged sessions will appear here, newest first.',
  },
  progress: {
    title: 'Progress',
    empty: 'Charts of your lifts, runs and personal records will appear here.',
  },
  body: {
    title: 'Body',
    todayWeight: "Today's weight",
    date: 'Date',
    log: 'Log',
    logged: (kg: string) => `Logged ${kg}`,
    invalidWeight: 'Enter a weight in kg, for example 82.4',
    chartTitle: 'Bodyweight',
    daily: 'Daily',
    weeklyAvg: 'Weekly average',
    goal: 'Goal',
    recent: 'Recent entries',
    delete: 'Delete',
    noEntries: 'No weigh-ins yet. Log your first one above.',
    plateau:
      'Your weekly average hasn’t dropped in 2 weeks. A small calorie reduction (about 100–200 kcal a day) may get things moving again.',
    trackingOff: 'Bodyweight tracking is turned off. Turn it on in Settings.',
  },
  settings: {
    title: 'Settings',

    syncSection: 'Sync',
    status: 'Status',
    lastSynced: 'Last synced',
    never: 'Not yet this session',
    lastError: 'Last error',
    syncNow: 'Sync now',

    profileSection: 'Profile',
    displayName: 'Name',
    timezone: 'Timezone',
    trackBodyweight: 'Track bodyweight',
    goalKg: 'Goal weight (kg)',
    goalNone: 'None',

    backupSection: 'Backup',
    download: 'Download my data (JSON)',
    import: 'Import from backup',
    imported: (n: number, skipped: number) =>
      `Imported ${n} ${n === 1 ? 'item' : 'items'}${skipped ? `, ${skipped} already up to date` : ''}.`,
    importFailed: (msg: string) => `Import failed: ${msg}`,

    plansLink: 'Training plans',
    accountSection: 'Account',
    signedInAs: 'Signed in as',
    changePassword: 'Change password',
    logOut: 'Log out',
    logOutBlocked: (n: number) =>
      `${n} ${n === 1 ? 'change hasn’t' : 'changes haven’t'} synced yet. Connect to the internet and wait for "All saved ✓" before logging out, or they will be lost.`,
    deleteAccount: 'Delete account',
    deleteWarning:
      'This permanently deletes your account and all your plans, workouts and weigh-ins. Download a backup first if you want to keep them. This cannot be undone.',
    deleteConfirmLabel: 'Type DELETE to confirm',
    deleteConfirmWord: 'DELETE',
    deleteForever: 'Delete my account',

    appInfo: 'App',
    version: 'Version',
    installed: 'Opened from Home Screen',
    persistentStorage: 'Persistent storage',
    yes: 'Yes',
    no: 'No',
    unknown: 'Unknown',
  },

  update: {
    available: 'A new version is available.',
    reload: 'Reload',
    offlineReady: 'Ready to work offline.',
    dismiss: 'Dismiss',
  },

  notFound: 'Page not found.',
} as const;
